MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(1, 'URL', 0);
MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(2, 'Username', 0);
MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(3, 'Password', 1);
MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(4, 'Docker Host', 0);
MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(5, 'Docker TLS Verify', 0);
MERGE INTO CONNECTION_PROPERTIES KEY (ID) VALUES(6, 'Docker Cert Path', 0);

MERGE INTO CONNECTION_TYPES KEY (ID) VALUES(1, 'DynamoDB (Local)', 'DYNAMODB_LOCAL', 'dynamoDBLocalConnectionFactory');
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(1, 1, 1);

MERGE INTO CONNECTION_TYPES KEY (ID) VALUES(2, 'Docker', 'DOCKER', 'dockerConnectionFactory');
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(2, 4, 0);
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(2, 5, 0);
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(2, 6, 0);

MERGE INTO CONNECTION_TYPES KEY (ID) VALUES(3, 'PostgreSQL', 'POSTGRESQL', 'postgresqlConnectionFactory');
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(3, 1, 1);
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(3, 2, 1);
MERGE INTO CONNECTION_TYPE_PROPERTIES KEY (TYPE_ID, PROPERTY_ID) VALUES(3, 3, 1);
